package:
  schema: 1
  name: "Rust (Binary)"
  slug: "rust-bin"
  flavor: "base"
  version: "1.76.0"
  description: "A language empowering everyone to build reliable and efficient software"
  homepage: "https://www.rust-lang.org/"
  checksum: ca9cf1047235d5afdc9e6315b9b2b6e4b665cc45b549bf7bc37373f6794cd392

sources:
  - name: "rust_binary"
    url: "https://static.rust-lang.org/dist/rust-1.76.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256: "9d589d2036b503cc45ecc94992d616fb3deec074deb36cacc2f5c212408f7399"

dependencies:
- commit: x86_64/bash/5.2.21/bootstrap/phase3/bundles/dev
  name: bash
- commit: x86_64/coreutils/9.5/bootstrap/phase3/bundles/dev
  name: coreutils
- commit: x86_64/findutils/4.9.0/bootstrap/phase3/bundles/dev
  name: findutils
- commit: x86_64/2nex-utilities/0.0.1/bootstrap/phase3/bundles/dev
  name: 2nex-utilities
- commit: x86_64/grep/3.11/bootstrap/phase3/bundles/dev
  name: grep
- commit: x86_64/gzip/1.13/bootstrap/phase3/bundles/dev
  name: gzip
- commit: x86_64/tar/1.35/bootstrap/phase3/bundles/dev
  name: tar
- commit: x86_64/glibc/2.39/bootstrap/phase3/bundles/dev
  name: glibc
- commit: x86_64/gcc/13.2.0/bootstrap/phase3/bundles/dev
  name: gcc
- commit: x86_64/sed/4.9/bootstrap/phase3/bundles/dev
  name: sed
- commit: x86_64/inetutils/2.5/bootstrap/phase3/bundles/dev
  name: inetutils
- commit: x86_64/acl/2.3.2/bootstrap/phase3/bundles/dev
  name: acl
- commit: x86_64/attr/2.5.2/bootstrap/phase3/bundles/dev
  name: attr
- commit: x86_64/gmp/6.3.0/bootstrap/phase3/bundles/dev
  name: gmp
- commit: x86_64/mpfr/4.2.1/bootstrap/phase3/bundles/dev
  name: mpfr
- commit: x86_64/mpc/1.2.1/bootstrap/phase3/bundles/dev
  name: mpc
- commit: x86_64/ncurses/6.4-20230520/bootstrap/phase3/bundles/dev
  name: ncurses

build:
  script: |
    # Extract the Rust archive
    mkdir -p "${WORK_DIR}/rust"
    tar --no-same-owner -xf ${SOURCE_rust_binary} -C "${WORK_DIR}/rust" --strip-components=1
    cd "${WORK_DIR}/rust"
    
    # Run the installer script with a prefix for the output dir
    ./install.sh --prefix=${OUT_DIR}/usr --without=rust-docs
    
    # Set consistent timestamps for reproducible builds
    find "${OUT_DIR}" -exec touch -d '2024-01-01T00:00:00+00:00' {} \;
    2nex_strip_binaries ${OUT_DIR}

bundles:
  full:
    - lib
    - static
    - misc
    - man
    - bin
    - conf
    - doc
  dev:
    - lib
    - static
    - misc
    - bin
    - conf

outputs:
  misc:
    - /usr/share/zsh/site-functions/_cargo
  lib:
    - /usr/lib/libLLVM-17-rust-1.76.0-stable.so
    - /usr/lib/librustc_driver-ef0b2e016afc8182.so
    - /usr/lib/libstd-66d8041607d2929b.so
    - /usr/lib/libtest-5d722ce3e5d0595e.so
    - /usr/lib/rustlib/components
    - /usr/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
    - /usr/lib/rustlib/etc/gdb_lookup.py
    - /usr/lib/rustlib/etc/gdb_providers.py
    - /usr/lib/rustlib/etc/lldb_commands
    - /usr/lib/rustlib/etc/lldb_lookup.py
    - /usr/lib/rustlib/etc/lldb_providers.py
    - /usr/lib/rustlib/etc/rust_types.py
    - /usr/lib/rustlib/install.log
    - /usr/lib/rustlib/manifest-cargo
    - /usr/lib/rustlib/manifest-clippy-preview
    - /usr/lib/rustlib/manifest-llvm-tools-preview
    - /usr/lib/rustlib/manifest-rls-preview
    - /usr/lib/rustlib/manifest-rust-analysis-x86_64-unknown-linux-gnu
    - /usr/lib/rustlib/manifest-rust-analyzer-preview
    - /usr/lib/rustlib/manifest-rust-demangler-preview
    - /usr/lib/rustlib/manifest-rust-docs-json-preview
    - /usr/lib/rustlib/manifest-rust-std-x86_64-unknown-linux-gnu
    - /usr/lib/rustlib/manifest-rustc
    - /usr/lib/rustlib/manifest-rustfmt-preview
    - /usr/lib/rustlib/rust-installer-version
    - /usr/lib/rustlib/uninstall.sh
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/analysis/removed.json
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-17-rust-1.76.0-stable.so
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-1ff34b0cf871cb60.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-349c574f342b0d30.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e9d126c51bb8b2bb.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7e6330a6c0cb9441.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-13fc9d1ed9c7a2bc.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-693a8f23970c5917.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-76f5006e4e062e57.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-0c110dd0650d6cb7.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-ce1d65fb391ae98b.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-39c59240bfdfab27.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-516789932d161b4e.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-306712ebb1ee1a3f.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-dcd9be90ae2cb505.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_abort-8819389c8540b63e.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a57e2388c0aea9b1.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-88465515ad9cec89.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libprofiler_builtins-7548e7c6d04551ba.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a6e97aae2681ad8f.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-8933a2fb54d88492.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-5af394d9b1f07bdc.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-a14b8d31733ef9e9.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-66d8041607d2929b.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-66d8041607d2929b.so
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-b93dac2525ec4d1e.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsysroot-88820e1c19a98c1d.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-5d722ce3e5d0595e.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-5d722ce3e5d0595e.so
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-a18ed5fdf4a57b72.rlib
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-65c422a3ad95273d.rlib
  bin:
    - /usr/bin/cargo
    - /usr/bin/cargo-clippy
    - /usr/bin/cargo-fmt
    - /usr/bin/clippy-driver
    - /usr/bin/rls
    - /usr/bin/rust-analyzer
    - /usr/bin/rust-demangler
    - /usr/bin/rust-gdb
    - /usr/bin/rust-gdbgui
    - /usr/bin/rust-lldb
    - /usr/bin/rustc
    - /usr/bin/rustdoc
    - /usr/bin/rustfmt
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld.lld
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/ld64.lld
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/lld-link
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/wasm-ld
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llc
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-ar
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-as
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-dis
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objcopy
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objdump
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-readobj
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-size
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-strip
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/opt
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
    - /usr/libexec/rust-analyzer-proc-macro-srv
  static:
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-stable_rt.asan.a
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-stable_rt.lsan.a
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-stable_rt.msan.a
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-stable_rt.safestack.a
    - /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-stable_rt.tsan.a
  doc:
    - /usr/share/doc/cargo/LICENSE-APACHE
    - /usr/share/doc/cargo/LICENSE-MIT
    - /usr/share/doc/cargo/LICENSE-THIRD-PARTY
    - /usr/share/doc/cargo/README.md
    - /usr/share/doc/clippy/LICENSE-APACHE
    - /usr/share/doc/clippy/LICENSE-MIT
    - /usr/share/doc/clippy/README.md
    - /usr/share/doc/rls/LICENSE-APACHE
    - /usr/share/doc/rls/LICENSE-MIT
    - /usr/share/doc/rls/README.md
    - /usr/share/doc/rust-analyzer/LICENSE-APACHE
    - /usr/share/doc/rust-analyzer/LICENSE-MIT
    - /usr/share/doc/rust-analyzer/README.md
    - /usr/share/doc/rust-demangler/LICENSE-APACHE
    - /usr/share/doc/rust-demangler/LICENSE-MIT
    - /usr/share/doc/rust-demangler/README.md
    - /usr/share/doc/rust/COPYRIGHT
    - /usr/share/doc/rust/LICENSE-APACHE
    - /usr/share/doc/rust/LICENSE-MIT
    - /usr/share/doc/rust/README.md
    - /usr/share/doc/rust/json/alloc.json
    - /usr/share/doc/rust/json/core.json
    - /usr/share/doc/rust/json/proc_macro.json
    - /usr/share/doc/rust/json/std.json
    - /usr/share/doc/rust/json/test.json
    - /usr/share/doc/rustfmt/LICENSE-APACHE
    - /usr/share/doc/rustfmt/LICENSE-MIT
    - /usr/share/doc/rustfmt/README.md
  man:
    - /usr/share/man/man1/cargo-add.1
    - /usr/share/man/man1/cargo-bench.1
    - /usr/share/man/man1/cargo-build.1
    - /usr/share/man/man1/cargo-check.1
    - /usr/share/man/man1/cargo-clean.1
    - /usr/share/man/man1/cargo-doc.1
    - /usr/share/man/man1/cargo-fetch.1
    - /usr/share/man/man1/cargo-fix.1
    - /usr/share/man/man1/cargo-generate-lockfile.1
    - /usr/share/man/man1/cargo-help.1
    - /usr/share/man/man1/cargo-init.1
    - /usr/share/man/man1/cargo-install.1
    - /usr/share/man/man1/cargo-locate-project.1
    - /usr/share/man/man1/cargo-login.1
    - /usr/share/man/man1/cargo-logout.1
    - /usr/share/man/man1/cargo-metadata.1
    - /usr/share/man/man1/cargo-new.1
    - /usr/share/man/man1/cargo-owner.1
    - /usr/share/man/man1/cargo-package.1
    - /usr/share/man/man1/cargo-pkgid.1
    - /usr/share/man/man1/cargo-publish.1
    - /usr/share/man/man1/cargo-remove.1
    - /usr/share/man/man1/cargo-report.1
    - /usr/share/man/man1/cargo-run.1
    - /usr/share/man/man1/cargo-rustc.1
    - /usr/share/man/man1/cargo-rustdoc.1
    - /usr/share/man/man1/cargo-search.1
    - /usr/share/man/man1/cargo-test.1
    - /usr/share/man/man1/cargo-tree.1
    - /usr/share/man/man1/cargo-uninstall.1
    - /usr/share/man/man1/cargo-update.1
    - /usr/share/man/man1/cargo-vendor.1
    - /usr/share/man/man1/cargo-verify-project.1
    - /usr/share/man/man1/cargo-version.1
    - /usr/share/man/man1/cargo-yank.1
    - /usr/share/man/man1/cargo.1
    - /usr/share/man/man1/rustc.1
    - /usr/share/man/man1/rustdoc.1
  conf:
    - /usr/etc/bash_completion.d/cargo

