package:
  schema: 1
  name: "CA Certificates"
  slug: "ca-certificates"
  flavor: "base"
  version: "20241223"
  description: "Certificate Authority certificates for SSL/TLS"
  homepage: "https://packages.debian.org/sid/ca-certificates"
  checksum: ddf040ae1b1de2c325d5af8f85ec12c79d70fe7b2dbebeb9a3b319a727dd68b6

sources:
  - name: "ca_certificates"
    url: "https://mirrors.edge.kernel.org/debian/pool/main/c/ca-certificates/ca-certificates_20250419.tar.xz"
    sha256: 33b44ef78653ecd3f0f2f13e5bba6be466be2e7da72182f737912b81798ba5d2

dependencies:
- commit: x86_64/bash/5.2.21/bootstrap/phase3/bundles/dev
  name: bash
- commit: x86_64/coreutils/9.5/bootstrap/phase3/bundles/dev
  name: coreutils
- commit: x86_64/findutils/4.9.0/bootstrap/phase3/bundles/dev
  name: findutils
- commit: x86_64/2nex-utilities/0.0.1/bootstrap/phase3/bundles/dev
  name: 2nex-utilities
- commit: x86_64/tar/1.35/bootstrap/phase3/bundles/dev
  name: tar
- commit: x86_64/glibc/2.39/bootstrap/phase3/bundles/dev
  name: glibc
- commit: x86_64/gcc/13.2.0/bootstrap/phase3/bundles/dev
  name: gcc
- commit: x86_64/ncurses/6.4-20230520/bootstrap/phase3/bundles/dev
  name: ncurses
- commit: x86_64/inetutils/2.5/bootstrap/phase3/bundles/dev
  name: inetutils
- commit: x86_64/attr/2.5.2/bootstrap/phase3/bundles/dev
  name: attr
- commit: x86_64/acl/2.3.2/bootstrap/phase3/bundles/dev
  name: acl
- commit: x86_64/mpc/1.2.1/bootstrap/phase3/bundles/dev
  name: mpc
- commit: x86_64/mpfr/4.2.1/bootstrap/phase3/bundles/dev
  name: mpfr
- commit: x86_64/gmp/6.3.0/bootstrap/phase3/bundles/dev
  name: gmp
- commit: x86_64/xz/5.4.6/bootstrap/phase3/bundles/dev
  name: xz
- commit: x86_64/gawk/5.3.0/bootstrap/phase3/bundles/dev
  name: gawk

build:
  script: |
    tar --no-same-owner -xf ${SOURCE_ca_certificates} -C "${WORK_DIR}" --strip-components=1
    cd ${WORK_DIR}
    
    # Install
    mkdir -p ${OUT_DIR}/usr/share/ca-certificates
    mkdir -p ${OUT_DIR}/etc/ssl/certs
    
    # Install certificates
    cp -a mozilla/* ${OUT_DIR}/usr/share/ca-certificates/
    
    # Generate ca-certificates.crt file
    cd ${OUT_DIR}/usr/share/ca-certificates
    find . -name "*.crt" | LC_ALL=C sort > ${OUT_DIR}/etc/ca-certificates.conf
    cd ${WORK_DIR}
    
    # Use openssl to create certificate bundle
    awk '{print "mozilla/" $0}' ${OUT_DIR}/etc/ca-certificates.conf | \
      while read crt; do \
        cat ${OUT_DIR}/usr/share/ca-certificates/$crt >> ${OUT_DIR}/etc/ssl/certs/ca-certificates.crt; \
        echo >> ${OUT_DIR}/etc/ssl/certs/ca-certificates.crt; \
      done
    
    # Create individual certificate symlinks
    cd ${OUT_DIR}/etc/ssl/certs
    for cert in $(find ${OUT_DIR}/usr/share/ca-certificates -name "*.crt"); do
      filename=$(basename "$cert")
      hash=$(openssl x509 -hash -noout -in "$cert")
      ln -sf ../../../usr/share/ca-certificates/mozilla/$filename $hash.0
    done
    
    # Set consistent timestamps for reproducible builds
    find "${OUT_DIR}" -exec touch -d '2024-01-01T00:00:00+00:00' {} \;

bundles:
  full:
    - conf
    - misc
  dev:
    - conf
    - misc

outputs:
  conf:
    files:
    - /etc/ca-certificates.conf
  misc:
    files:
    - /usr/share/ca-certificates/Makefile
    - /usr/share/ca-certificates/blacklist.txt
    - /usr/share/ca-certificates/certdata.txt
    - /usr/share/ca-certificates/certdata2pem.py
    - /usr/share/ca-certificates/nssckbi.h
