package:
  schema: 1
  name: "GDBM"
  slug: "gdbm"
  flavor: "sys-libs"
  version: "1.23"
  description: "GNU dbm is a set of database routines that use extensible hashing"
  homepage: "https://www.gnu.org/software/gdbm/"
  checksum: e0f6100452193e91bb8cb38b1015efeb8d5dfc5f0f2cd6fd653678bb983d3c04

sources:
  - name: "gdbm"
    url: "https://ftp.gnu.org/gnu/gdbm/gdbm-1.23.tar.gz"
    sha256: "74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd"

dependencies:
- commit: x86_64/coreutils/9.5/bootstrap/phase1/bundles/dev
  name: coreutils
- commit: x86_64/findutils/4.9.0/bootstrap/phase1/bundles/dev
  name: findutils
- commit: x86_64/2nex-utilities/0.0.1/sys-apps/bundles/dev
  name: 2nex-utilities
- commit: x86_64/gawk/5.3.0/bootstrap/phase1/bundles/dev
  name: gawk
- commit: x86_64/gzip/1.13/bootstrap/phase1/bundles/dev
  name: gzip
- commit: x86_64/make/4.4.1/bootstrap/phase1/bundles/dev
  name: make
- commit: x86_64/tar/1.35/bootstrap/phase1/bundles/dev
  name: tar
- commit: x86_64/texinfo/7.1/bootstrap/phase2/bundles/dev
  name: texinfo
- commit: x86_64/glibc/2.39/sys-libs/bundles/dev
  name: glibc
- commit: x86_64/zlib/1.3.1/bootstrap/phase3/bundles/dev
  name: zlib
- commit: x86_64/bzip2/1.0.8/bootstrap/phase3/bundles/dev
  name: bzip2
- commit: x86_64/xz/5.4.6/bootstrap/phase3/bundles/dev
  name: xz
- commit: x86_64/file/5.45/bootstrap/phase3/bundles/dev
  name: file
- commit: x86_64/binutils/2.42/bootstrap/phase3/bundles/dev
  name: binutils
- commit: x86_64/gmp/6.3.0/sys-libs/bundles/dev
  name: gmp
- commit: x86_64/mpfr/4.2.1/bootstrap/phase3/bundles/dev
  name: mpfr
- commit: x86_64/mpc/1.2.1/bootstrap/phase3/bundles/dev
  name: mpc
- commit: x86_64/attr/2.5.2/sys-libs/bundles/dev
  name: attr
- commit: x86_64/acl/2.3.2/sys-libs/bundles/dev
  name: acl
- commit: x86_64/gcc/13.2.0/bootstrap/phase3/bundles/dev
  name: gcc
- commit: x86_64/linux-headers/6.4.1/bootstrap/phase3/bundles/dev
  name: linux
- commit: x86_64/ncurses/6.4-20230520/sys-libs/bundles/dev
  name: ncurses
- commit: x86_64/sed/4.9/sys-apps/bundles/dev
  name: sed
- commit: x86_64/grep/3.11/sys-apps/bundles/dev
  name: grep
- commit: x86_64/bash/5.2.21/app-shells/bundles/dev
  name: bash

build:
  script: |
    tar --no-same-owner -xf ${SOURCE0} -C "${WORK_DIR}" --strip-components=1
    cd ${WORK_DIR}

    ./configure --prefix=/usr    \
                --disable-static \
                --enable-libgdbm-compat
    make
    make DESTDIR=$OUT_DIR install
    
    find "${OUT_DIR}" -exec touch -d "2024-01-01T00:00:00+00:00" {} \;
    2nex_strip_binaries ${OUT_DIR}

bundles:
  full:
    - info
    - locale
    - man
    - dev
    - bin
    - lib

  dev:
    - dev
    - bin
    - lib

outputs:
  info:
    files:
    - /usr/share/info/dir
    - /usr/share/info/gdbm.info
  locale:
    files:
    - /usr/share/locale/da/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/de/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/eo/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/es/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/fi/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/fr/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/ja/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/pl/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/pt_BR/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/ru/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/sr/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/sv/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/uk/LC_MESSAGES/gdbm.mo
    - /usr/share/locale/vi/LC_MESSAGES/gdbm.mo
  man:
    files:
    - /usr/share/man/man1/gdbm_dump.1
    - /usr/share/man/man1/gdbm_load.1
    - /usr/share/man/man1/gdbmtool.1
    - /usr/share/man/man3/gdbm.3
  dev:
    files:
    - /usr/include/dbm.h
    - /usr/include/gdbm.h
    - /usr/include/ndbm.h
    - /usr/lib/libgdbm.la
    - /usr/lib/libgdbm_compat.la
  bin:
    files:
    - /usr/bin/gdbm_dump
    - /usr/bin/gdbm_load
    - /usr/bin/gdbmtool
    requires:
    - x86_64/glibc/2.39/sys-libs/outputs/lib
  lib:
    files:
    - /usr/lib/libgdbm.so
    - /usr/lib/libgdbm.so.6
    - /usr/lib/libgdbm.so.6.0.0
    - /usr/lib/libgdbm_compat.so
    - /usr/lib/libgdbm_compat.so.4
    - /usr/lib/libgdbm_compat.so.4.0.0
    requires:
    - x86_64/glibc/2.39/sys-libs/outputs/lib
