package:
  schema: 1
  name: "Automake"
  slug: "automake"
  flavor: "sys/devel"
  version: "1.16.5"
  description: "A tool for automatically generating Makefile.in files compliant with the GNU Coding Standards"
  homepage: "https://www.gnu.org/software/automake/"
  checksum: ff5f2a50887f0d6e9e9d6c89d680d201b2c60ab7debb0515b1098f185989e2d3

sources:
  - name: "automake"
    url: "https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz"
    sha256: "f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469"


dependencies:
- commit: x86_64/findutils/4.9.0/bootstrap/phase1/bundles/dev
  name: findutils
- commit: x86_64/bash/5.2.21/bootstrap/phase1/bundles/dev
  name: bash
- commit: x86_64/2nex-utilities-bootstrap/0.0.1/bootstrap/phase3/bundles/dev
  name: 2nex-utilities-bootstrap
- commit: x86_64/gawk/5.3.0/bootstrap/phase1/bundles/dev
  name: gawk
- commit: x86_64/make/4.4.1/bootstrap/phase1/bundles/dev
  name: make
- commit: x86_64/tar/1.35/bootstrap/phase1/bundles/dev
  name: tar
- commit: x86_64/coreutils/9.5/bootstrap/phase1/outputs/bin
  name: coreutils
- commit: x86_64/texinfo/7.1/bootstrap/phase2/bundles/dev
  name: texinfo
- commit: x86_64/m4/1.4.19/bootstrap/phase3/bundles/dev
  name: m4
- commit: x86_64/gcc/13.2.0/bootstrap/phase3/outputs/lib
  name: gcc
- commit: x86_64/sed/4.9/bootstrap/phase1/bundles/dev
  name: sed
- commit: x86_64/grep/3.11/bootstrap/phase1/bundles/dev
  name: grep
- commit: x86_64/perl/5.38.2/bootstrap/phase2/bundles/dev
  name: perl
- commit: x86_64/autoconf/2.72/sys/devel/bundles/dev
  name: autoconf
- commit: x86_64/glibc/2.39/sys/libs/bundles/dev
  name: glibc
- commit: x86_64/xz/5.4.6/bootstrap/phase1/bundles/dev
  name: xz

build:
  script: |
    tar --no-same-owner -xf ${SOURCE0} -C "${WORK_DIR}" --strip-components=1
    cd ${WORK_DIR}

    ./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.16.5
    make
    make DESTDIR=$OUT_DIR install
    
    find "${OUT_DIR}" -exec touch -d "2024-01-01T00:00:00+00:00" {} \;
    2nex_strip_binaries ${OUT_DIR}

bundles:

  full:
    - man
    - bin
    - doc
    - info
    - dev

  dev:
    - bin
    - dev

outputs:
  man:
    files:
    - /usr/share/man/man1/aclocal-1.16.1
    - /usr/share/man/man1/aclocal.1
    - /usr/share/man/man1/automake-1.16.1
    - /usr/share/man/man1/automake.1
  bin:
    files:
    - /usr/bin/aclocal
    - /usr/bin/aclocal-1.16
    - /usr/bin/automake
    - /usr/bin/automake-1.16
  doc:
    files:
    - /usr/share/doc/automake-1.16.5/amhello-1.0.tar.gz
  info:
    files:
    - /usr/share/info/automake-history.info
    - /usr/share/info/automake.info
    - /usr/share/info/automake.info-1
    - /usr/share/info/automake.info-2
    - /usr/share/info/dir
  dev:
    files:
    - /usr/share/aclocal-1.16/amversion.m4
    - /usr/share/aclocal-1.16/ar-lib.m4
    - /usr/share/aclocal-1.16/as.m4
    - /usr/share/aclocal-1.16/auxdir.m4
    - /usr/share/aclocal-1.16/cond-if.m4
    - /usr/share/aclocal-1.16/cond.m4
    - /usr/share/aclocal-1.16/depend.m4
    - /usr/share/aclocal-1.16/depout.m4
    - /usr/share/aclocal-1.16/dmalloc.m4
    - /usr/share/aclocal-1.16/extra-recurs.m4
    - /usr/share/aclocal-1.16/gcj.m4
    - /usr/share/aclocal-1.16/init.m4
    - /usr/share/aclocal-1.16/install-sh.m4
    - /usr/share/aclocal-1.16/internal/ac-config-macro-dirs.m4
    - /usr/share/aclocal-1.16/lead-dot.m4
    - /usr/share/aclocal-1.16/lex.m4
    - /usr/share/aclocal-1.16/lispdir.m4
    - /usr/share/aclocal-1.16/maintainer.m4
    - /usr/share/aclocal-1.16/make.m4
    - /usr/share/aclocal-1.16/missing.m4
    - /usr/share/aclocal-1.16/mkdirp.m4
    - /usr/share/aclocal-1.16/obsolete.m4
    - /usr/share/aclocal-1.16/options.m4
    - /usr/share/aclocal-1.16/prog-cc-c-o.m4
    - /usr/share/aclocal-1.16/python.m4
    - /usr/share/aclocal-1.16/runlog.m4
    - /usr/share/aclocal-1.16/sanity.m4
    - /usr/share/aclocal-1.16/silent.m4
    - /usr/share/aclocal-1.16/strip.m4
    - /usr/share/aclocal-1.16/substnot.m4
    - /usr/share/aclocal-1.16/tar.m4
    - /usr/share/aclocal-1.16/upc.m4
    - /usr/share/aclocal-1.16/vala.m4
    - /usr/share/aclocal/README
    - /usr/share/automake-1.16/Automake/ChannelDefs.pm
    - /usr/share/automake-1.16/Automake/Channels.pm
    - /usr/share/automake-1.16/Automake/Condition.pm
    - /usr/share/automake-1.16/Automake/Config.pm
    - /usr/share/automake-1.16/Automake/Configure_ac.pm
    - /usr/share/automake-1.16/Automake/DisjConditions.pm
    - /usr/share/automake-1.16/Automake/FileUtils.pm
    - /usr/share/automake-1.16/Automake/General.pm
    - /usr/share/automake-1.16/Automake/Getopt.pm
    - /usr/share/automake-1.16/Automake/Item.pm
    - /usr/share/automake-1.16/Automake/ItemDef.pm
    - /usr/share/automake-1.16/Automake/Language.pm
    - /usr/share/automake-1.16/Automake/Location.pm
    - /usr/share/automake-1.16/Automake/Options.pm
    - /usr/share/automake-1.16/Automake/Rule.pm
    - /usr/share/automake-1.16/Automake/RuleDef.pm
    - /usr/share/automake-1.16/Automake/VarDef.pm
    - /usr/share/automake-1.16/Automake/Variable.pm
    - /usr/share/automake-1.16/Automake/Version.pm
    - /usr/share/automake-1.16/Automake/Wrap.pm
    - /usr/share/automake-1.16/Automake/XFile.pm
    - /usr/share/automake-1.16/COPYING
    - /usr/share/automake-1.16/INSTALL
    - /usr/share/automake-1.16/am/check.am
    - /usr/share/automake-1.16/am/check2.am
    - /usr/share/automake-1.16/am/clean-hdr.am
    - /usr/share/automake-1.16/am/clean.am
    - /usr/share/automake-1.16/am/compile.am
    - /usr/share/automake-1.16/am/configure.am
    - /usr/share/automake-1.16/am/data.am
    - /usr/share/automake-1.16/am/dejagnu.am
    - /usr/share/automake-1.16/am/depend.am
    - /usr/share/automake-1.16/am/depend2.am
    - /usr/share/automake-1.16/am/distdir.am
    - /usr/share/automake-1.16/am/footer.am
    - /usr/share/automake-1.16/am/header-vars.am
    - /usr/share/automake-1.16/am/header.am
    - /usr/share/automake-1.16/am/inst-vars.am
    - /usr/share/automake-1.16/am/install.am
    - /usr/share/automake-1.16/am/java.am
    - /usr/share/automake-1.16/am/lang-compile.am
    - /usr/share/automake-1.16/am/lex.am
    - /usr/share/automake-1.16/am/library.am
    - /usr/share/automake-1.16/am/libs.am
    - /usr/share/automake-1.16/am/libtool.am
    - /usr/share/automake-1.16/am/lisp.am
    - /usr/share/automake-1.16/am/ltlib.am
    - /usr/share/automake-1.16/am/ltlibrary.am
    - /usr/share/automake-1.16/am/mans-vars.am
    - /usr/share/automake-1.16/am/mans.am
    - /usr/share/automake-1.16/am/program.am
    - /usr/share/automake-1.16/am/progs.am
    - /usr/share/automake-1.16/am/python.am
    - /usr/share/automake-1.16/am/remake-hdr.am
    - /usr/share/automake-1.16/am/scripts.am
    - /usr/share/automake-1.16/am/subdirs.am
    - /usr/share/automake-1.16/am/tags.am
    - /usr/share/automake-1.16/am/texi-vers.am
    - /usr/share/automake-1.16/am/texibuild.am
    - /usr/share/automake-1.16/am/texinfos.am
    - /usr/share/automake-1.16/am/vala.am
    - /usr/share/automake-1.16/am/yacc.am
    - /usr/share/automake-1.16/ar-lib
    - /usr/share/automake-1.16/compile
    - /usr/share/automake-1.16/config.guess
    - /usr/share/automake-1.16/config.sub
    - /usr/share/automake-1.16/depcomp
    - /usr/share/automake-1.16/install-sh
    - /usr/share/automake-1.16/mdate-sh
    - /usr/share/automake-1.16/missing
    - /usr/share/automake-1.16/mkinstalldirs
    - /usr/share/automake-1.16/py-compile
    - /usr/share/automake-1.16/tap-driver.sh
    - /usr/share/automake-1.16/test-driver
    - /usr/share/automake-1.16/texinfo.tex
    - /usr/share/automake-1.16/ylwrap
