[package]
name = "nex-builder"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/source"]
resolver = "2"

[dependencies]
blake3 = "1.5"
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.17"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.34"
sha2 = "0.10.8"
tempfile = "3.10.1"
walkdir = "2.5.0"
nex-source = { path = "crates/source" }
zub = { package = "zub-store", git = "https://github.com/wegel/zub.git", rev = "89d8b5e", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
