package:
  schema: 1
  name: "kmod"
  slug: "kmod"
  flavor: "sys-kernel"
  version: "32"
  description: "Linux kernel module handling"
  homepage: "https://github.com/kmod-project/kmod"
  checksum: 139ce9b15a8e66500ec7d02e7ae964b220d1dae09bd6593992bef62b2a80035f

sources:
  - name: "kmod"
    url: "https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-32.tar.xz"
    sha256: "630ed0d92275a88cb9a7bf68f5700e911fdadaf02e051cf2e4680ff8480bd492"

dependencies:
- commit: x86_64/coreutils/9.5/bootstrap/phase1/bundles/dev
  name: coreutils
- commit: x86_64/findutils/4.9.0/bootstrap/phase1/bundles/dev
  name: findutils
- commit: x86_64/2nex-utilities/0.0.1/sys-apps/bundles/dev
  name: 2nex-utilities
- commit: x86_64/gawk/5.3.0/bootstrap/phase1/bundles/dev
  name: gawk
- commit: x86_64/make/4.4.1/bootstrap/phase1/bundles/dev
  name: make
- commit: x86_64/tar/1.35/bootstrap/phase1/bundles/dev
  name: tar
- commit: x86_64/glibc/2.39/sys-libs/bundles/dev
  name: glibc
- commit: x86_64/zlib/1.3.1/bootstrap/phase3/bundles/dev
  name: zlib
- commit: x86_64/bzip2/1.0.8/bootstrap/phase3/bundles/dev
  name: bzip2
- commit: x86_64/xz/5.4.6/bootstrap/phase3/bundles/dev
  name: xz
- commit: x86_64/zstd/1.5.6/bootstrap/phase3/bundles/dev
  name: zstd
- commit: x86_64/file/5.45/bootstrap/phase3/bundles/dev
  name: file
- commit: x86_64/pkgconf/2.2.0/bootstrap/phase3/bundles/dev
  name: pkgconf
- commit: x86_64/binutils/2.42/bootstrap/phase3/bundles/dev
  name: binutils
- commit: x86_64/gmp/6.3.0/sys-libs/bundles/dev
  name: gmp
- commit: x86_64/mpfr/4.2.1/bootstrap/phase3/bundles/dev
  name: mpfr
- commit: x86_64/mpc/1.2.1/bootstrap/phase3/bundles/dev
  name: mpc
- commit: x86_64/attr/2.5.2/sys-libs/bundles/dev
  name: attr
- commit: x86_64/acl/2.3.2/sys-libs/bundles/dev
  name: acl
- commit: x86_64/gcc/13.2.0/bootstrap/phase3/bundles/dev
  name: gcc
- commit: x86_64/linux-headers/6.4.1/bootstrap/phase3/bundles/dev
  name: linux
- commit: x86_64/ncurses/6.4-20230520/sys-libs/bundles/dev
  name: ncurses
- commit: x86_64/sed/4.9/sys-apps/bundles/dev
  name: sed
- commit: x86_64/grep/3.11/sys-apps/bundles/dev
  name: grep
- commit: x86_64/bash/5.2.21/app-shells/bundles/dev
  name: bash
- commit: x86_64/openssl3/3.3.1/dev-libs/bundles/dev
  name: openssl3

build:
  script: |
    tar --no-same-owner -xf ${SOURCE0} -C "${WORK_DIR}" --strip-components=1
    cd ${WORK_DIR}

    ldconfig
    ./configure --prefix=/usr          \
            --sysconfdir=/etc      \
            --with-openssl         \
            --with-xz              \
            --with-zstd            \
            --with-zlib
    make
    make  DESTDIR=$OUT_DIR install

    find "${OUT_DIR}" -exec touch -d "2024-01-01T00:00:00+00:00" {} \;
    2nex_strip_binaries ${OUT_DIR}

bundles:
  full:
    - lib
    - misc
    - man
    - dev
    - bin

  dev:
    - lib
    - bin
    - dev
    
outputs:
  lib:
    files:
    - /usr/lib/libkmod.so
    - /usr/lib/libkmod.so.2
    - /usr/lib/libkmod.so.2.4.2
    requires:
    - x86_64/gcc/13.2.0/bootstrap/phase3/outputs/lib
    - x86_64/glibc/2.39/sys-libs/outputs/lib
    - x86_64/openssl3/3.3.1/dev-libs/outputs/lib
    - x86_64/xz/5.4.6/bootstrap/phase3/outputs/lib
    - x86_64/zlib/1.3.1/bootstrap/phase3/outputs/lib
    - x86_64/zstd/1.5.6/bootstrap/phase3/outputs/lib
  misc:
    files:
    - /usr/share/bash-completion/completions/kmod
  man:
    files:
    - /usr/share/man/man5/depmod.d.5
    - /usr/share/man/man5/modprobe.d.5
    - /usr/share/man/man5/modules.dep.5
    - /usr/share/man/man5/modules.dep.bin.5
    - /usr/share/man/man8/depmod.8
    - /usr/share/man/man8/insmod.8
    - /usr/share/man/man8/kmod.8
    - /usr/share/man/man8/lsmod.8
    - /usr/share/man/man8/modinfo.8
    - /usr/share/man/man8/modprobe.8
    - /usr/share/man/man8/rmmod.8
  dev:
    files:
    - /usr/include/libkmod.h
    - /usr/lib/libkmod.la
    - /usr/lib/pkgconfig/kmod.pc
    - /usr/lib/pkgconfig/libkmod.pc
  bin:
    files:
    - /usr/bin/depmod
    - /usr/bin/insmod
    - /usr/bin/kmod
    - /usr/bin/lsmod
    - /usr/bin/modinfo
    - /usr/bin/modprobe
    - /usr/bin/rmmod
    requires:
    - x86_64/gcc/13.2.0/bootstrap/phase3/outputs/lib
    - x86_64/glibc/2.39/sys-libs/outputs/lib
    - x86_64/openssl3/3.3.1/dev-libs/outputs/lib
    - x86_64/xz/5.4.6/bootstrap/phase3/outputs/lib
    - x86_64/zlib/1.3.1/bootstrap/phase3/outputs/lib
    - x86_64/zstd/1.5.6/bootstrap/phase3/outputs/lib
