[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/wegel/zub?rev=78a5374"]
git = "https://github.com/wegel/zub"
rev = "78a5374"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
