[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/wegel/zub?rev=8027343ae5ee5db46c0969c2ebeaa721e4a6e0d6"]
git = "https://github.com/wegel/zub"
rev = "8027343ae5ee5db46c0969c2ebeaa721e4a6e0d6"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
