[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/wegel/zub.git?rev=0db2a06aa0b741eb537ef41e5864226586aced38"]
git = "https://github.com/wegel/zub.git"
rev = "0db2a06aa0b741eb537ef41e5864226586aced38"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
