[package]
name = "nex-source"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
flate2 = "1.1.9"
fs2 = "0.4.3"
sha2 = "0.10.8"
tar = "=0.4.44"
tempfile = "3.27.0"
toml = "0.8.23"
walkdir = "2.5.0"
zip = { version = "8.6.0", default-features = false, features = ["deflate-flate2"] }

[dev-dependencies]
tempfile = "3.27.0"
